sonar.projectKey=angular-learning
sonar.projectName=Angular Learning Project
sonar.projectVersion=1.0

sonar.sources=src
sonar.sourceEncoding=UTF-8

sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=**/node_modules/**,**/*.spec.ts

sonar.host.url=http://localhost:9000

sonar.token=squ_59675ddc257cc6fd758e8b60faa0abb4d8b1caf0